---
- name: "debian ngnix signing key"
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key

- name: "debian nginx repository"
  apt_repository:
    repo: "{{item}}"
  with_items:
    - deb http://nginx.org/packages/mainline/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
    - deb-src http://nginx.org/packages/mainline/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx

- name: "install nginx"
  package:
    name: nginx
    state: latest
  notify: "start nginx"